version: '3'
services:
  elasticrating:
    build:
      context: elastic-rating-services
      dockerfile: Dockerfile
      args:
        JAR_FILE : target/elastic-rating-services.jar
    image: elastic-rating-services
    ports:
      - "8080:8080"
    network_mode: host
    depends_on:
      - "elasticsearch"

  kibana:
    image: kibana:5.6.9
    environment: ['ELASTICSEARCH_URL=http://127.0.0.1:9200']
    ports:
      - "5601:5601"
    depends_on:
      - "elasticsearch"
    network_mode: host

  elasticsearch:
      image: elasticsearch:5.6.9
      environment: ['ES_JAVA_OPTS=-Xms500m -Xmx500m']
      ports:
        - "9200:9200"
        - "9300:9300"
      network_mode: host